version: '3.7'

services:
  web:
    build: .
    command: gunicorn dockerDjango.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: mysql:5.7
    user: "1000:50"
    volumes:
    - mysql_data:/var/lib/minesql/data
    environment:
      - ./.env.prod.db

volumes:
  mysql_data: