version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: mysql:5.7
    user: "1000:50"
    volumes:
    - mysql_data:/var/lib/minesql/data
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=django
      - MYSQL_PASSWORD=django
      - MYSQL_DATABASE=docker_django

volumes:
  mysql_data: